name: mind_soul_relaxation
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 # Add this line (check for latest version)
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  fl_chart: ^0.66.0  # 📊 For visualizing meditation statistics
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/animations/MeditatingGiraffe.json
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon.png

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash_logo.png
  android: true
  ios: true

